### ISSUE TITLE
Update conversion macro

### ISSUE THREAD

**Issue by ginnocen** [AliceO2Group/DelphesO2#28]
hi @njacazio, could you update the conversion of the tables? I spotted in particular that the missing tpcNClsFound variable creates problems in the O2 processing cause all these tracks are removed by the track selection. We would need to force it true

**Comment by njacazio** [comment]
Hi, indeed, the `tpcNClsFound` is dynamically defined in the O2 table so it should be taken inside of the framework.

`DECLARE_SOA_DYNAMIC_COLUMN(TPCNClsFound, tpcNClsFound, [](uint8_t tpcNClsFindable, int8_t tpcNClsFindableMinusFound) -> int16_t { return (int16_t)tpcNClsFindable - tpcNClsFindableMinusFound; });
`
I don't think it is there in the AO2Ds as well.
![image](https://user-images.githubusercontent.com/1282257/104884664-08dae980-5967-11eb-9582-6f7192c2b854.png)

However, there is a selection task for ALICE3 that we can already use in the O2 https://github.com/AliceO2Group/AliceO2/blob/dev/Analysis/Tasks/ALICE3/alice3-trackselection.cxx maybe we can update that one by removing the TPC requirement which will probably not be there anyway. What do you think?
