### ISSUE TITLE
Need to check return status of smearTrack

### ISSUE THREAD

**Issue by preghenella** [AliceO2Group/DelphesO2#29]
https://github.com/preghenella/DelphesO2/blob/926e029b2845ae9633ae4437279c05f44358309e/examples/aod/createO2tables.C#L162

@njacazio 
please check the return status of this line, which should be considered invalid if not `true`
if (!smearTrack) continue;

**Comment by njacazio** [comment]
https://github.com/preghenella/DelphesO2/pull/30 should fix it
